config/routes.rb
Rails.application.routes.draw do
  get 'my_orders/:id', as: 'my_order', to: 'my_orders#show'

  post 'carrito/add', to: 'in_shopping_carts#add', as: 'add_to_shopping_cart'
  delete 'carrito/product', to: 'in_shopping_carts#delete', as:"remove_in_shopping_carts_product"
  put 'carrito', to: 'in_shopping_carts#update', as: 'update_in_shopping_cart'

  get 'categories', to: 'categories#index'
  get 'categories/:name', to: 'categories#show', as: "category"

  get 'search', to: "search#index"
  post 'search', to:"search#search"

  get 'carrito', to: "shopping_carts#show"

  post 'payments/check_out', to: 'payments#check_out', as:"check_out"
  get 'payments/execute', to: 'payments#execute', as:"execute_payment"

  resources :products
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
end

app/models/shopping_cart.rb
# == Schema Information
#
# Table name: shopping_carts
#
#  id         :integer          not null, primary key
#  status     :integer          default("0")
#  ip         :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class ShoppingCart < ApplicationRecord
  has_many :in_shopping_carts
  has_many :products, through: :in_shopping_carts


  enum status: {payed: 1, created: 0}

  def total
    total = 0
    self.in_shopping_carts.each do |i_sh|
      total += i_sh.product.pricing * i_sh.quantity
    end

    if total >= 1000
      return total

    else
      return total + 150
    end

  end

  def subtotal
    subtotal = 0
    self.in_shopping_carts.each do |i_sh|
      subtotal += i_sh.product.pricing * i_sh.quantity
    end
    return subtotal
  end

  def shipping_discount
    return self.total != self.subtotal ? 0 : 150
  end

  def items
    arr = []
    self.products.each do |product|
      arr << {name: product.title, sku: product.id, price: product.pricing, currency: "MXN", quantity: self.in_shopping_carts.find_by(product_id: product.id).quantity}
    end
    return arr
  end

end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
end

app/helpers/shopping_carts_helper.rb
module ShoppingCartsHelper
end

app/views/shopping_carts/show.haml
.container
  .card.white.big-padding.top-space

    -if @shopping_cart.products.blank?
      %h2 Tu carrito aun no tiene productos

    -else
      %h1.text-center Carrito de compras
      %table.table.table-hover
        %thead
          %tr
            %td
              Producto
            %td
              Precio unitario
            %td
              Cantidad
            %td
              Total del producto
            %td
        %tbody
          -@shopping_cart.products.each.with_index do |product, i|
            %tr
              %td= product.title
              %td
                $
                = product.pricing
                %div.unit{id: "unit_#{@shopping_cart.in_shopping_carts[i].id}", style: "display: none;"}= product.pricing

              %td
                =number_field_tag :quantity, @shopping_cart.in_shopping_carts[i].quantity, min: 1, onchange:"$.ajax({url: \"#{update_in_shopping_cart_path}\", method: \"PUT\", data: {in_shopping_cart: #{@shopping_cart.in_shopping_carts[i].id}, quantity: this.value}, dataType: 'script'})", id: "quantity_#{@shopping_cart.in_shopping_carts[i].id}", class: "quantity"

              %td
                $
                %span.product_total{id:"productTotal_#{@shopping_cart.in_shopping_carts[i].id}"}= (product.pricing * @shopping_cart.in_shopping_carts[i].quantity)
              %td= link_to "Eliminar", remove_in_shopping_carts_product_path(id: @shopping_cart.in_shopping_cart_ids[i]), method: :delete, class:"red-text"





          %tr
            %td
              %strong Subtotal:

            %td
              %strong
                $
                %span#subtotal= @shopping_cart.subtotal

          %tr
            %td
              Envio:
            %td#delivery
              -if @shopping_cart.subtotal >= 1000
                Gratis

              -else
                + $150

          %tr
            %td
              %strong Total:

            %td
              %strong
                $
                %span#total= @shopping_cart.total
      .center-xs
        %span.bigger.text-center Pagar
        %br
        =link_to check_out_path, class:"btn teal", method: :post do
          Pagar con
          =image_tag "paypal_logo_small", width: 75