config/routes.rb
Rails.application.routes.draw do
  get 'my_orders/:id', as: 'my_order', to: 'my_orders#show'

  post 'carrito/add', to: 'in_shopping_carts#add', as: 'add_to_shopping_cart'
  delete 'carrito/product', to: 'in_shopping_carts#delete', as:"remove_in_shopping_carts_product"
  put 'carrito', to: 'in_shopping_carts#update', as: 'update_in_shopping_cart'

  get 'categories', to: 'categories#index'
  get 'categories/:name', to: 'categories#show', as: "category"

  get 'search', to: "search#index"
  post 'search', to:"search#search"

  get 'carrito', to: "shopping_carts#show"

  post 'payments/check_out', to: 'payments#check_out', as:"check_out"
  get 'payments/execute', to: 'payments#execute', as:"execute_payment"

  resources :products
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in? && !current_user.client?
      @products = Product.all
      @orders = MyOrder.all
      return render "home/admin"
    else
      @products = Product.all
      return render "home/index"
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/admin.haml
.row.center-xs.top-space
  .col-xs-11
    .box
      .row
        .col-xs-12.col-md-12.col-lg-4.teal.white-text{style:"padding: 1em;"}
          .box
            .row
              .col-xs-8
                .box
                  %h2
                    Products
              .col-xs-4
                .box
                  %a.btn.btn-success.btn-fab{href: new_product_path}
                    %i.material-icons add


              .col-xs-12
                .box
                  %table.table.table-stripped
                    %thead
                      %tr
                        %th Product
                        %th.text-center Stock
                        %th
                    %tbody
                      -@products.each do |product|
                        %tr
                          %td.text-left= product.title
                          %td.text-center= product.stock
                          %td.lext-right
                            = link_to "Editar", edit_product_path(id: product.id), class:"lighter-blue-text bold"
        .col-xs-12.col-md-12.col-lg-8.dark-blue.white-text{style:"padding: 1em;"}
          .box
            .row
              .col-xs-12.col-md-6.col-lg-12
                .box
                  %h2
                    Incomplete orders


                  .panel-group#incompleted_orders{role: "tablist", aria:{multiselectable: true}}
                    -@orders.where("status = ?", 0).each do |order|
                      .panel
                        %a{role: "button", data: {toggle: "collapse", parent:"#incompleted_orders"}, aria:{expanded: "false", controls: "collapse_incompleted_#{order.id}"}, href: "#collapse_incompleted_#{order.id}"}
                          .panel-heading.light-blue.white-text{role: "tab", id: "heading_incompleted_#{order.id}"}
                            %span.panel-title
                              =order.recipient_name
                        .panel-collapse.collapse{id: "collapse_incompleted_#{order.id}", role:"tabpanel", aria:{labelledby: "heading_incompleted_#{order.id}"}}
                          .panel-body.lighter-blue.black-text
                            =order.permanent_link

              .col-xs-12.col-md-6.col-lg-12
                .box
                  %h2
                    Completed orders

                  .panel-group#completed_orders{role: "tablist", aria:{multiselectable: true}}
                    -@orders.where("status = ?", 1).each do |order|
                      .panel
                        %a{role: "button", data: {toggle: "collapse", parent:"#completed_orders"}, aria:{expanded: "false", controls: "collapse_completed_#{order.id}"}, href: "#collapse_completed_#{order.id}"}
                          .panel-heading.light-blue.white-text{role: "tab", id: "heading_completed_#{order.id}"}
                            %span.panel-title
                              =order.recipient_name
                        .panel-collapse.collapse{id: "collapse_completed_#{order.id}", role:"tabpanel", aria:{labelledby: "heading_completed_#{order.id}"}}
                          .panel-body.lighter-blue.black-text
                            =order.permanent_link

app/views/home/index.haml
.green.big-padding.no-margin
  %h2.text-center Ultimos productos
.row.center-xs.light-blue.big-padding
  .col-xs-10
    .box
      #galeria
        .inner
          -@products.order("created_at DESC").limit(5).each do |prod|
            -if prod.avatars.any?
              .image{style:"background-image: url('#{url_to_image(prod.avatars.first.image.url)}');", onclick:"window.location.replace('#{product_path(id: prod.id)}')"}