config/routes.rb
Rails.application.routes.draw do
  get 'my_orders/:id', as: 'my_order', to: 'my_orders#show'

  post 'carrito/add', to: 'in_shopping_carts#add', as: 'add_to_shopping_cart'
  delete 'carrito/product', to: 'in_shopping_carts#delete', as:"remove_in_shopping_carts_product"
  put 'carrito', to: 'in_shopping_carts#update', as: 'update_in_shopping_cart'

  get 'categories', to: 'categories#index'
  get 'categories/:name', to: 'categories#show', as: "category"

  get 'search', to: "search#index"
  post 'search', to:"search#search"

  get 'carrito', to: "shopping_carts#show"

  post 'payments/check_out', to: 'payments#check_out', as:"check_out"
  get 'payments/execute', to: 'payments#execute', as:"execute_payment"

  resources :products
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ApplicationRecord
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find_by(name: params[:name]) or not_found
    @products = Product.where("category = ?", @category.name)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.haml
.row.center-xs
  .col-xs-11.col-md-10.col-lg-9
    .box
      .panel.panel-info
        .panel-heading
          %h1.panel-title Categorias
        -@categories.each do |category|
          =link_to category_path(name: category.name), class:"btn", style:"margin: 0; width: 100%; border-bottom: 1px solid grey;" do
            .panel-body
              %h2.responsive{style:"margin: 0;"}= category.name

app/views/categories/show.haml
%h1.text-center= @category.name.capitalize
.center-xs
  =link_to "Regresar", categories_path, class:"btn btn-link indigo-text"
.row.center-xs
  .col-xs-11
    .box
      .row.center-xs
        -if !@products.empty?
          -@products.each do |product|
            .col-xs-12-col-md-6.col-lg-4
              .box
                .thumbnail
                  -if product.avatars.any?
                    =image_tag product.avatars.first.image.url(:medium), class:"top-space"
                  -else
                    =image_tag "missing", class:"top-space"
                  .caption
                    %h3= product.title
                    %span
                      $
                      =product.pricing
                    %p.truncated.text-justify.responsive= product.description.gsub(/\n/, '<br>').html_safe()
                    %p
                      =link_to "Agregar al carrito", add_to_shopping_cart_path(product_id: product.id), method: :post, class:"btn btn-success"
                      =link_to "Ver mas...", product_path(id: product.id), class:"btn btn-info"
        -else
          %span.bigger Upss parece que aun no hay ningun producto en esta categoria