config/routes.rb
Rails.application.routes.draw do
  get 'my_orders/:id', as: 'my_order', to: 'my_orders#show'

  post 'carrito/add', to: 'in_shopping_carts#add', as: 'add_to_shopping_cart'
  delete 'carrito/product', to: 'in_shopping_carts#delete', as:"remove_in_shopping_carts_product"
  put 'carrito', to: 'in_shopping_carts#update', as: 'update_in_shopping_cart'

  get 'categories', to: 'categories#index'
  get 'categories/:name', to: 'categories#show', as: "category"

  get 'search', to: "search#index"
  post 'search', to:"search#search"

  get 'carrito', to: "shopping_carts#show"

  post 'payments/check_out', to: 'payments#check_out', as:"check_out"
  get 'payments/execute', to: 'payments#execute', as:"execute_payment"

  resources :products
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  pricing     :integer
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  stock       :integer
#  category    :string
#

class Product < ApplicationRecord
  belongs_to :user
  has_many :avatars
  has_many :in_shopping_carts
  has_many :shopping_carts, through: :in_shopping_carts

  validates_presence_of :title, :description
  validates :pricing, numericality: {greater_than: 0}
  validates :stock, numericality: {greater_than: -1}

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.user = current_user

    respond_to do |format|
      if @product.save

        if params[:images]
          params[:images].each do |image|
            @product.avatars.create(image: image)
          end

        end

        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    if @product.user == current_user
      respond_to do |format|

        if params[:images]
          @product.avatars.each do |avatar|
            avatar.destroy
          end
          params[:images].each do |image|
            @product.avatars.create(image: image)
          end

        end

        if @product.update(product_params)
          format.html { redirect_to @product, notice: 'Product was successfully updated.' }
          format.json { render :show, status: :ok, location: @product }
        else
          format.html { render :edit }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    else
      return redirect_to(root_path)
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :pricing, :user_id, :images, :category, :stock)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.haml
= form_for @product, html: { multipart: true } do |f|
  - if @product.errors.any?
    #error_explanation
      %h2= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg

  .row.big-padding
    .col-xs-12.col-md-8
      .box
        .form-group
          = f.text_field :title, class:"form-control floating-label", placeholder: "Título"

    .col-xs-12.col-md-4
      .box
        .form-group
          .input-group
            %span.input-group-addon $
            = f.number_field :pricing, class:"form-control floating-label", placeholder: "Costo", step: 1
            %span.input-group-addon MXN

    .col-xs-6
      .box
        .form-group
          .input-group
            %span.input-group-addon Stock
            = f.number_field :stock, class:"form-control floating-label", placeholder: "Stock", step: 1


    .col-xs-6
      .box
        .form-group
          .input-group
            %span.input-group-addon Cateoria
            = f.select :category, [],{}, {placeholder: "Categoria", class:"form-control"} do
              =Category.all.each do |cat|
                %option{value: cat.name}= cat.name

    .col-xs-12
      .box
        .form-group
          = f.text_area :description, class:"form-control big-padding floating-label", placeholder:"Descripción", rows:"15"

    .col-xs-12.center-xs
      .box
        .form-group
          = label_tag "images[]", class:"btn btn-inverse" do
            Seleccionar imagenes
          = file_field_tag "images[]", class:"hidden", multiple: true
    .col-xs-12.center-xs
      .box
        = f.submit "Guardar", class:"btn btn-info"

app/views/products/edit.html.haml
.row.center-xs
  .col-xs-11.col-md-10
    .card.top-space
      %h1.text-center Editing product
      = render 'form'
      .center-xs
        = link_to 'Show', @product
        \|
        = link_to 'Back', products_path

app/views/products/index.html.haml
.container
  .row.center-xs
    -@products.each do |product|
      .col-xs-12.col-md-6.col-lg-4.top-space
        .box
          .thumbnail
            -if product.avatars.any?
              =image_tag product.avatars.first.image.url(:medium), class:"top-space"
            -else
              =image_tag "missing", class:"top-space"
            .caption
              %h3= product.title
              %span
                $
                =product.pricing
              %p.truncated.text-justify.responsive= product.description.gsub(/\n/, '<br>').html_safe()
              %p
                =link_to "Agregar al carrito", add_to_shopping_cart_path(product_id: product.id), method: :post, class:"btn btn-success"
                =link_to "Ver mas...", product_path(id: product.id), class:"btn btn-info"

app/views/products/new.html.haml
%h1 New product

= render 'form'

= link_to 'Back', products_path

app/views/products/show.html.haml
.row.center-xs.top-space.bottom-space
  .col-xs-11.col-md-9.text-justify
    .card.big-padding
      %h1.text-center= @product.title
      .row
        .col-xs-12.col-md-6
          .box
            .row
              -if @product.avatars.any?
                .col-xs-12.col-md-2
                  .box
                    -@product.avatars.each.with_index do |avatar, i|
                      =image_tag avatar.image.url(:thumb), class:"inline-block images-previews square", id: "prev-#{i}"
                .col-xs-12.col-md-10.center-xs
                  .box
                    -@product.avatars.each.with_index do |avatar, i|
                      %a.lightbox-image{href:"#{image_url(avatar.image.url(:medium))}"}
                        =image_tag avatar.image.url(:medium), class:"inline-block hidden products-images", id:"img-#{i}"
              -else
                .col-xs-2
                  .box
                    =image_tag "missing", class:"inline-block images-previews square", id: "prev-#{0}"
                .col-xs-10.center-xs
                  .box
                    =image_tag "missing", class:"inline-block hidden products-images", id:"img-#{0}"



        .col-xs-12.col-md-6
          .box
            %span.responsive
              Precio:
              %strong.red-text
                $
                ='%.2f' % @product.pricing
              -if @product.pricing >= 500
                %strong Envio gratis.
              -else
                Pueden aplicarse
                %strong cargos por envio.
            %br
            %span.responsive Descripción:
            %br
            %p.responsive.inline-block=  @product.description.gsub(/\n/, '<br>').gsub("bold{", "<strong>").gsub("}bold", "</strong>").html_safe()

      .row
        .col-xs-8.col-xs-offset-2.col-md-6.col-md-offset-5.col-lg-4.col-lg-offset-7
          .box
            =link_to "Agregar al carrito", add_to_shopping_cart_path(product_id: @product.id), method: :post, class:"btn btn-success"